name: Daily crawl

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.8"

      - name: Install Chrome for Selenium
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y --allow-downgrades ./google-chrome-stable_current_amd64.deb
          
      - name: Install pipenv
        run: |
          python -m pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run python script
        run: |
          pipenv run python main.py

      - name: Commit new rss file
        run: |
          git config --global user.name 'Github Action Runner'
          git add feeds
          git commit -m "Generated new feed $(date -I)"
          git push
